language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm run build-all
- npm run release-linux-x64
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: ./client/bin
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
    tags: true
- provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*.{zip,tar.xz}
  on:
    branch: master
    tags: true
- provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true