language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm run build-all
deploy:
  provider: pages
  local_dir: ./client/bin
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: false
  on:
    branch: master
  provider: releases
  api_key: $GITHUB_TOKEN
  file: release.zip
  skip_cleanup: true
  on:
    branch: master